@url = http://localhost:5000/api
@storyId = 98b8511a-413d-44c8-80bd-cb332bdd3507

###
GET {{url}}

###
GET {{url}}/stories

###
GET {{url}}/stories/{{storyId}}

###
POST {{url}}/stories
Content-Type: application/json

{
  "title": "Story 1",
  "text": "Lorem ipsum",
  "author": "user1",
  "tags": ["tag1", "tag2"]
}