@url = http://localhost:5000/api
@storyId = e9fc0d1d-882e-4384-890a-34574dadcbed

###
GET {{url}}

###
GET {{url}}/stories

###
GET {{url}}/stories/{{storyId}}

###
POST {{url}}/stories
Content-Type: application/json

{
  "title": "Story 1",
  "text": "Lorem ipsum",
  "author": "user1",
  "tags": ["tag1", "tag2"]
}